spring.application.name=odontologia-app

server.port=8080
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/odontologodb
spring.datasource.username=postgres
spring.datasource.password=admin
#https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
spring.jpa.open-in-view=true
#Se especifica si las tablas son creadas automaticamente basadas en las Entities
spring.jpa.generate-ddl=false
# Establece que la base de datos no se genere automaticamente la DB.
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#Specify explicitly the dialect (here for PostgreSQL, adapt for your database)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
